### ISSUE TITLE
Publishing 0.5.0

### ISSUE THREAD

**Issue by LoganDark** [j-tai/getargs#9]
Thought I'd open this issue to track the days till 0.5.0's release. :)

Hopefully it's coming out soon!

**Comment by LoganDark** [comment]
Got a weekend to knock this out?

**Comment by LoganDark** [comment]
Poke (it is the weekend now)

**Comment by j-tai** [comment]
Published, hopefully no disasters happen

**Comment by LoganDark** [comment]
> Published, hopefully no disasters happen

Other than the commits you made that I'm quite unhappy for missing. (see #10 for longer explanation)

It's not that bad so no need to make another release fixing it. That would be really, really sad (imagine if the 0.5.0 release got ruined by a tiny last-minute change).
